/**
 * GET /api/projects/[launchId]/ceo-briefing
 * Returns the most recent CEO briefing generated by the autonomous cycle.
 */

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { db } from "@/db";
import { launchProjectsTable } from "@/db/schema/launch-schema";
import { eq, and } from "drizzle-orm";
import type { CEOBriefing } from "@/db/schema/launch-schema";

export const dynamic = "force-dynamic";

export async function GET(
  _req: NextRequest,
  { params }: { params: { launchId: string } },
) {
  const { userId } = await auth();
  if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const [project] = await db
    .select()
    .from(launchProjectsTable)
    .where(and(eq(launchProjectsTable.id, params.launchId), eq(launchProjectsTable.userId, userId)));

  if (!project) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const results  = (project.stageResults ?? {}) as Record<string, unknown>;
  const briefing = (results.ceoBriefing ?? null) as CEOBriefing | null;

  return NextResponse.json({ briefing });
}
