"use client";

import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import {
  Sparkles, Store, Megaphone, Mail,
  ShieldCheck, CreditCard, Repeat, Package, ArrowRight,
} from "lucide-react";
import Link from "next/link";

/* ─── helpers ─── */
function FadeUp({ children, delay = 0, className = "" }: {
  children: React.ReactNode; delay?: number; className?: string;
}) {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-60px" });
  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 28 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.6, delay, ease: [0.22, 1, 0.36, 1] }}
      className={className}
    >
      {children}
    </motion.div>
  );
}

/* ─── Value proposition cards — all 100% factual ─── */
const VALUE_CARDS = [
  {
    icon: ShieldCheck,
    color: "text-orange-400",
    bg: "bg-orange-500/10",
    border: "border-orange-500/20",
    title: "7-Day Free Trial",
    desc: "Try every feature before you pay. No credit card required to start.",
  },
  {
    icon: CreditCard,
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    border: "border-blue-500/20",
    title: "One Subscription",
    desc: "Everything included in a single monthly price. No per-sale fees, no hidden add-ons.",
  },
  {
    icon: Sparkles,
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/20",
    title: "AI Product Creator",
    desc: "Describe your idea. AI writes and formats a complete digital product — ebook, planner, template, or guide.",
  },
  {
    icon: Store,
    color: "text-green-400",
    bg: "bg-green-500/10",
    border: "border-green-500/20",
    title: "Your Own Storefront",
    desc: "A branded store at yourname.contentflywheel.co.uk. Stripe payments go directly to your bank.",
  },
  {
    icon: Megaphone,
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    border: "border-purple-500/20",
    title: "Marketing Tools Included",
    desc: "Content calendar, video scripts, social captions, and promo assets — all generated by AI.",
  },
  {
    icon: Mail,
    color: "text-pink-400",
    bg: "bg-pink-500/10",
    border: "border-pink-500/20",
    title: "Email Marketing Built In",
    desc: "Collect subscribers and send campaigns directly from the platform. No Mailchimp required.",
  },
  {
    icon: Users,
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/20",
    title: "Affiliate Programme",
    desc: "Built-in referral tracking and discount codes. Let your customers grow your audience for you.",
  },
  {
    icon: Package,
    color: "text-teal-400",
    bg: "bg-teal-500/10",
    border: "border-teal-500/20",
    title: "Marketplace Included",
    desc: "List your products on the Content Flywheel marketplace to reach buyers beyond your own audience.",
  },
  {
    icon: Repeat,
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    border: "border-rose-500/20",
    title: "Cancel Anytime",
    desc: "No long-term contracts. Cancel from your dashboard whenever you want. No questions asked.",
  },
];

/* ─── Beta trust cards ─── */
const BETA_CARDS = [
  {
    emoji: "🚀",
    title: "Early Access",
    desc: "Join before public launch and help shape the product. Your feedback directly influences what gets built next.",
    border: "border-orange-500/20",
    bg: "bg-orange-500/[0.04]",
    glow: "hover:border-orange-500/40",
  },
  {
    emoji: "💬",
    title: "Direct Founder Feedback",
    desc: "Every piece of feedback is reviewed personally. If something doesn't work, we want to know — and we'll fix it.",
    border: "border-blue-500/20",
    bg: "bg-blue-500/[0.04]",
    glow: "hover:border-blue-500/40",
  },
  {
    emoji: "⚡",
    title: "Weekly Improvements",
    desc: "New features, fixes and improvements are shipped regularly throughout the beta. The product improves every week.",
    border: "border-purple-500/20",
    bg: "bg-purple-500/[0.04]",
    glow: "hover:border-purple-500/40",
  },
];

/* ─── Main export ─── */
export function StatsAndProof() {
  return (
    <>
      {/* ─── Value proposition grid ─── */}
      <section className="py-24 lg:py-32 relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-6">
          <FadeUp className="text-center mb-16">
            <p className="text-xs font-bold uppercase tracking-widest text-orange-500 mb-4">What you get</p>
            <h2 className="text-4xl lg:text-5xl font-extrabold text-white tracking-tight">
              Everything a digital creator needs.{" "}
              <span className="bg-gradient-to-r from-orange-400 to-amber-400 bg-clip-text text-transparent">
                Nothing you don&apos;t.
              </span>
            </h2>
            <p className="mt-4 text-lg text-white/40 max-w-xl mx-auto">
              One subscription. No hidden fees. Every tool in the list below is included.
            </p>
          </FadeUp>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {VALUE_CARDS.map((card, i) => {
              const Icon = card.icon;
              return (
                <FadeUp key={card.title} delay={i * 0.05}>
                  <div className={`flex items-start gap-4 p-5 rounded-2xl border ${card.border} bg-white/[0.02] hover:bg-white/[0.04] transition-colors h-full`}>
                    <div className={`w-10 h-10 rounded-xl ${card.bg} flex items-center justify-center shrink-0`}>
                      <Icon className={`w-5 h-5 ${card.color}`} />
                    </div>
                    <div>
                      <p className="text-sm font-bold text-white mb-1">{card.title}</p>
                      <p className="text-xs text-white/45 leading-relaxed">{card.desc}</p>
                    </div>
                  </div>
                </FadeUp>
              );
            })}
          </div>
        </div>
      </section>

      {/* ─── Beta trust section ─── */}
      <section className="py-24 lg:py-32 border-t border-white/[0.05] bg-white/[0.01]">
        <div className="max-w-5xl mx-auto px-6">

          {/* Heading */}
          <FadeUp className="text-center mb-14">
            <p className="text-xs font-bold uppercase tracking-widest text-orange-500 mb-4">Beta programme</p>
            <h2 className="text-4xl lg:text-5xl font-extrabold text-white tracking-tight">
              Built with our{" "}
              <span className="bg-gradient-to-r from-orange-400 to-amber-400 bg-clip-text text-transparent">
                first creators
              </span>
            </h2>
            <p className="mt-5 text-lg text-white/45 max-w-2xl mx-auto leading-relaxed">
              Content Flywheel is currently in beta. We&apos;re working closely with our first creators to improve every part of the platform based on real feedback.
            </p>
          </FadeUp>

          {/* Three cards */}
          <div className="grid sm:grid-cols-3 gap-5 mb-14">
            {BETA_CARDS.map((card, i) => (
              <FadeUp key={card.title} delay={i * 0.1}>
                <motion.div
                  whileHover={{ y: -2 }}
                  transition={{ duration: 0.2 }}
                  className={`relative rounded-2xl border ${card.border} ${card.bg} ${card.glow} p-7 h-full transition-colors overflow-hidden`}
                >
                  {/* Subtle top glow line */}
                  <div className="absolute top-0 left-6 right-6 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />

                  <div className="text-3xl mb-5 select-none">{card.emoji}</div>
                  <h3 className="text-base font-bold text-white mb-2">{card.title}</h3>
                  <p className="text-sm text-white/45 leading-relaxed">{card.desc}</p>
                </motion.div>
              </FadeUp>
            ))}
          </div>

          {/* CTA */}
          <FadeUp delay={0.3} className="text-center">
            <Link
              href="/signup"
              className="group inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-orange-500 to-amber-500 px-9 py-4 text-base font-bold text-white shadow-lg shadow-orange-500/25 transition hover:shadow-xl hover:shadow-orange-500/35 hover:scale-105"
            >
              Start your free 7-day trial
              <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" />
            </Link>
            <p className="mt-3 text-sm text-white/25">
              Become one of the first creators using Content Flywheel.
            </p>
          </FadeUp>

        </div>
      </section>
    </>
  );
}
