export const dynamic = "force-dynamic";
import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { checkApiRateLimit } from "@/lib/rate-limit-api";
import { db } from "@/db/db";
import { goalsTable, dailyTasksTable } from "@/db/schema/goals-schema";
import { eq, and, asc } from "drizzle-orm";

type TaskRow = {
  id: string;
  dayNumber: number;
  taskDescription: string;
  estimatedDuration: number | null;
  isCompleted: boolean;
  orderIndex: number;
  proofType: string | null;
  proofUrl: string | null;
  proofText: string | null;
  proofSubmittedAt: Date | null;
  completedAt: Date | null;
};

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildReportHtml(
  title: string,
  description: string | null,
  totalDays: number,
  longestStreak: number,
  targetDate: string,
  tasks: TaskRow[]
): string {
  const byDay: Record<number, TaskRow[]> = {};
  for (const t of tasks) {
    if (!byDay[t.dayNumber]) byDay[t.dayNumber] = [];
    byDay[t.dayNumber].push(t);
  }
  const days = Object.keys(byDay)
    .map(Number)
    .sort((a, b) => a - b);

  const daySections = days
    .map((day) => {
      const dayTasks = byDay[day];
      const taskRows = dayTasks
        .map((t) => {
          let proofHtml = "";
          if (t.proofType === "screenshot" && t.proofUrl) {
            proofHtml = `<div class="proof"><img src="${escapeHtml(t.proofUrl)}" alt="Proof" style="max-width:100%;height:auto;border:1px solid #e2e8f0;border-radius:8px;" /></div>`;
          } else if (t.proofType === "link" && t.proofUrl) {
            proofHtml = `<div class="proof">Link: <a href="${escapeHtml(t.proofUrl)}">${escapeHtml(t.proofUrl)}</a></div>`;
          } else if (t.proofType === "text" && t.proofText) {
            proofHtml = `<div class="proof">${escapeHtml(t.proofText).replace(/\n/g, "<br/>")}</div>`;
          } else if (t.proofSubmittedAt) {
            proofHtml = `<div class="proof">Proof submitted (${new Date(t.proofSubmittedAt).toLocaleString()})</div>`;
          }
          const completedLabel = t.isCompleted ? " ✓ Completed" : "";
          const completedAt = t.completedAt || t.proofSubmittedAt;
          const completedStr = completedAt
            ? ` — ${new Date(completedAt).toLocaleString()}`
            : "";
          return `
          <tr>
            <td class="task-desc">${escapeHtml(t.taskDescription)}${completedLabel}</td>
            <td class="task-meta">${t.estimatedDuration != null ? `${t.estimatedDuration} min` : ""} ${completedStr}</td>
          </tr>
          ${proofHtml ? `<tr><td colspan="2" class="proof-cell">${proofHtml}</td></tr>` : ""}
        `;
        })
        .join("");
      return `
        <section class="day-section">
          <h2>Day ${day}</h2>
          <table class="task-table">
            <tbody>${taskRows}</tbody>
          </table>
        </section>
      `;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Progress Report: ${escapeHtml(title)}</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 24px; color: #1e293b; line-height: 1.5; }
    h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
    .meta { color: #64748b; font-size: 0.875rem; margin-bottom: 24px; }
    .day-section { margin-bottom: 32px; break-inside: avoid; }
    .day-section h2 { font-size: 1.125rem; margin-bottom: 12px; color: #0f172a; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
    .task-table { width: 100%; border-collapse: collapse; }
    .task-table td { padding: 8px 0; vertical-align: top; }
    .task-desc { font-weight: 500; }
    .task-meta { font-size: 0.8125rem; color: #64748b; white-space: nowrap; }
    .proof-cell { padding-left: 16px; padding-bottom: 12px; }
    .proof { font-size: 0.875rem; margin-top: 4px; }
    .proof img { max-height: 280px; }
    @media print { body { padding: 16px; } .day-section { page-break-inside: avoid; } }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  ${description ? `<p class="meta">${escapeHtml(description)}</p>` : ""}
  <p class="meta">
    ${totalDays} days • Longest streak: ${longestStreak} days • Target date: ${escapeHtml(targetDate)}
  </p>
  ${daySections}
  <p class="meta" style="margin-top: 32px;">Generated by Content Flywheel — Goal Progress Report</p>
</body>
</html>`;
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { id } = await params;
    if (!id) return NextResponse.json({ error: "Goal ID required" }, { status: 400 });

    const [goal] = await db
      .select()
      .from(goalsTable)
      .where(and(eq(goalsTable.id, id), eq(goalsTable.userId, userId)));

    if (!goal) return NextResponse.json({ error: "Goal not found" }, { status: 404 });

    const tasks = await db
      .select({
        id: dailyTasksTable.id,
        dayNumber: dailyTasksTable.dayNumber,
        taskDescription: dailyTasksTable.taskDescription,
        estimatedDuration: dailyTasksTable.estimatedDuration,
        isCompleted: dailyTasksTable.isCompleted,
        orderIndex: dailyTasksTable.orderIndex,
        proofType: dailyTasksTable.proofType,
        proofUrl: dailyTasksTable.proofUrl,
        proofText: dailyTasksTable.proofText,
        proofSubmittedAt: dailyTasksTable.proofSubmittedAt,
        completedAt: dailyTasksTable.completedAt,
      })
      .from(dailyTasksTable)
      .where(eq(dailyTasksTable.goalId, id))
      .orderBy(asc(dailyTasksTable.dayNumber), asc(dailyTasksTable.orderIndex));

    const targetDate =
      goal.targetDate instanceof Date
        ? goal.targetDate.toISOString().slice(0, 10)
        : String(goal.targetDate);

    const html = buildReportHtml(
      goal.title,
      goal.description,
      goal.totalDays,
      goal.longestStreak,
      targetDate,
      tasks as TaskRow[]
    );

    const slug = goal.title.replace(/[^a-z0-9]+/gi, "-").slice(0, 40) || "goal";
    const filename = `goal-${slug}-progress-report.html`;

    return new NextResponse(html, {
      status: 200,
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (err) {
    console.error("Progress report error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Failed to generate report" },
      { status: 500 }
    );
  }
}
