"use client";

/**
 * CEOBriefingCard — Phase 7.0
 * ──────────────────────────────────────────────────────────────────────────────
 * Shows the most recent CEO briefing generated by the autonomous cycle.
 * Displays headline, summary, department roll-up, highlights, and next actions.
 */

import { useEffect, useState, useCallback } from "react";
import {
  Sparkles,
  CheckCircle2,
  XCircle,
  SkipForward,
  Lightbulb,
  ArrowRight,
  RefreshCw,
} from "lucide-react";
import type { CEOBriefing, AutonomousDepartment } from "@/db/schema/launch-schema";

/* ─── Types ──────────────────────────────────────────────────────────────────── */

type Props = { launchId: string };

/* ─── Helpers ────────────────────────────────────────────────────────────────── */

const DEPT_COLORS: Record<AutonomousDepartment, string> = {
  research:  "text-blue-600 dark:text-blue-400",
  marketing: "text-orange-600 dark:text-orange-400",
  design:    "text-pink-600 dark:text-pink-400",
  analytics: "text-emerald-600 dark:text-emerald-400",
  learning:  "text-violet-600 dark:text-violet-400",
  memory:    "text-amber-600 dark:text-amber-400",
  system:    "text-gray-500 dark:text-gray-400",
};

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-GB", {
    weekday: "long", month: "long", day: "numeric",
  });
}

function DeptStatusIcon({ status }: { status: "completed" | "failed" | "skipped" }) {
  if (status === "completed") return <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500 shrink-0" />;
  if (status === "failed")    return <XCircle      className="h-3.5 w-3.5 text-red-400 shrink-0" />;
  return <SkipForward className="h-3.5 w-3.5 text-gray-400 shrink-0" />;
}

/* ─── Component ──────────────────────────────────────────────────────────────── */

export function CEOBriefingCard({ launchId }: Props) {
  const [briefing,   setBriefing]   = useState<CEOBriefing | null>(null);
  const [loading,    setLoading]    = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async (force = false) => {
    if (force) setRefreshing(true);
    try {
      const res  = await fetch(`/api/projects/${launchId}/ceo-briefing`);
      const data = await res.json() as { briefing: CEOBriefing | null };
      setBriefing(data.briefing ?? null);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [launchId]);

  useEffect(() => { void load(); }, [load]);

  if (loading) {
    return (
      <div className="rounded-xl border border-[#E5E7EB] dark:border-[#1E1E1E] bg-white dark:bg-[#111] p-5 animate-pulse">
        <div className="h-5 w-64 bg-gray-200 dark:bg-gray-800 rounded mb-3" />
        <div className="h-12 bg-gray-100 dark:bg-gray-800 rounded mb-3" />
        <div className="grid grid-cols-2 gap-3">
          {[0,1,2,3].map(i => <div key={i} className="h-12 bg-gray-100 dark:bg-gray-800 rounded" />)}
        </div>
      </div>
    );
  }

  if (!briefing) {
    return (
      <div className="rounded-xl border border-[#E5E7EB] dark:border-[#1E1E1E] bg-white dark:bg-[#111] p-6 text-center">
        <Sparkles className="h-8 w-8 text-gray-300 dark:text-gray-700 mx-auto mb-2" />
        <p className="text-sm font-medium text-gray-500 dark:text-gray-400">No CEO briefing yet</p>
        <p className="text-xs text-gray-400 mt-1">Run your first autonomous cycle to generate a briefing.</p>
      </div>
    );
  }

  return (
    <div className="rounded-xl border border-[#E5E7EB] dark:border-[#1E1E1E] bg-white dark:bg-[#111] overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-5 py-3 border-b border-[#F0F0F0] dark:border-[#1E1E1E] bg-gradient-to-r from-slate-50 to-gray-50 dark:from-slate-950/30 dark:to-gray-950/30">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-yellow-500" />
          <span className="text-sm font-semibold text-gray-900 dark:text-white">CEO Briefing</span>
          <span className="text-[10px] text-gray-400">Cycle #{briefing.cycleNumber} · {formatDate(briefing.date)}</span>
        </div>
        <button
          onClick={() => void load(true)}
          disabled={refreshing}
          className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 disabled:opacity-50 transition-colors"
          title="Refresh"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${refreshing ? "animate-spin" : ""}`} />
        </button>
      </div>

      <div className="p-5 space-y-4">
        {/* Headline */}
        <div>
          <h3 className="text-base font-bold text-gray-900 dark:text-white leading-snug">
            {briefing.headline}
          </h3>
          <p className="text-sm text-gray-600 dark:text-gray-400 mt-1 leading-relaxed">
            {briefing.summary}
          </p>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-3 gap-2">
          {[
            { label: "Generated", value: briefing.itemsGenerated },
            { label: "Approved",  value: briefing.itemsApproved },
            { label: "Pending",   value: briefing.pendingApprovals, highlight: briefing.pendingApprovals > 0 },
          ].map(({ label, value, highlight }) => (
            <div
              key={label}
              className={`rounded-lg border p-2.5 text-center ${
                highlight
                  ? "border-orange-200 dark:border-orange-900/40 bg-orange-50 dark:bg-orange-950/20"
                  : "border-[#F0F0F0] dark:border-[#1E1E1E] bg-gray-50/50 dark:bg-[#0F0F0F]/50"
              }`}
            >
              <p className={`text-xl font-bold ${highlight ? "text-orange-600 dark:text-orange-400" : "text-gray-900 dark:text-white"}`}>
                {value}
              </p>
              <p className="text-[10px] text-gray-400 mt-0.5">{label}</p>
            </div>
          ))}
        </div>

        {/* Department roll-up */}
        <div>
          <p className="text-[10px] font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-2">
            Departments
          </p>
          <div className="space-y-1.5">
            {briefing.departments.map(dept => (
              <div key={dept.department} className="flex items-center gap-2">
                <DeptStatusIcon status={dept.status} />
                <span className={`text-xs font-medium w-20 shrink-0 ${DEPT_COLORS[dept.department]}`}>
                  {dept.name}
                </span>
                <span className="text-xs text-gray-500 dark:text-gray-400 truncate">{dept.output}</span>
                {dept.itemCount > 0 && (
                  <span className="ml-auto text-[10px] text-gray-400 shrink-0">{dept.itemCount} item{dept.itemCount !== 1 ? "s" : ""}</span>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Highlights */}
        {briefing.highlights.length > 0 && (
          <div className="rounded-lg border border-yellow-100 dark:border-yellow-900/20 bg-yellow-50/50 dark:bg-yellow-950/10 p-3">
            <div className="flex items-center gap-1.5 mb-2">
              <Lightbulb className="h-3.5 w-3.5 text-yellow-500" />
              <span className="text-[10px] font-semibold text-yellow-700 dark:text-yellow-400 uppercase tracking-wide">
                Highlights
              </span>
            </div>
            <ul className="space-y-1">
              {briefing.highlights.map((h, i) => (
                <li key={i} className="text-xs text-gray-700 dark:text-gray-300 flex items-start gap-1.5">
                  <span className="text-yellow-500 mt-0.5">•</span>
                  {h}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Next actions */}
        {briefing.nextActions.length > 0 && (
          <div>
            <p className="text-[10px] font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-2">
              Next Actions
            </p>
            <ul className="space-y-1">
              {briefing.nextActions.map((action, i) => (
                <li key={i} className="flex items-start gap-2 text-xs text-gray-700 dark:text-gray-300">
                  <ArrowRight className="h-3 w-3 text-orange-400 mt-0.5 shrink-0" />
                  {action}
                </li>
              ))}
            </ul>
          </div>
        )}

        <p className="text-[10px] text-gray-400">
          Generated {new Date(briefing.generatedAt).toLocaleString("en-GB")}
        </p>
      </div>
    </div>
  );
}
